### ISSUE TITLE
Rebuild the clients to expose the KNN functionality

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/openapi#12]
subj.

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-typescript/commit/7940e085a15278abed9f23dcf9e141a13c393ea0, https://github.com/manticoresoftware/manticoresearch-java/commit/3d02dea7b0791eb4ee3ec8ddd856760b32d486ad, https://github.com/manticoresoftware/manticoresearch-javascript/commit/5fecfdf8e78ad6719e29ac594c567d57a7a454ee, https://github.com/manticoresoftware/manticoresearch-net/commit/70b597cd592486b8bf939b0739da01b9875c2ff9, https://github.com/manticoresoftware/manticoresearch-python/commit/95a2c82d1a0b0e0a99a8619087fd1d4b7af73b4d
