### ISSUE TITLE
NICK will fix publishing dev versions for autogenerated clients

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/openapi#15]
It's currently impossible to republish the same dev version in most autogenerated clients. The task is to fix it by making the versions more specific, e.g. by adding datetime + commit to them:

```
# git log -1 --date=format:"%y%m%d%H" --format=%cd-%h|head
24030421-8ba538cc4
```

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-java/commit/976e6b98e87846044b7276ca6f26bcbd098c9bda, https://github.com/manticoresoftware/manticoresearch-python/commit/de847ad89f354d2d0f4c30dc7d4c00530fd21382, https://github.com/manticoresoftware/manticoresearch-typescript/commit/e2fd3e2b61757eac98746e8e18438ae11299de0d, https://github.com/manticoresoftware/manticoresearch-javascript/commit/e160dda6c26f13899d3587c57ae17221333e0e05
