### ISSUE TITLE
New OpenAPI schema for the clients

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/openapi#16]
Recently, we've been working on a few updates related to Manticore's HTTP API:
* https://github.com/manticoresoftware/manticoresearch/issues/1806
* https://github.com/manticoresoftware/manticoresearch/issues/1808,  
* https://github.com/manticoresoftware/manticoresearch/issues/1810,
* https://github.com/manticoresoftware/manticoresearch/issues/1811,
* https://github.com/manticoresoftware/manticoresearch/issues/1866.

That should allow us to abandon customizing the auto-generated clients we do now to handle ambiguities in HTTP API's response formats.   After all the above-mentioned issues are finished, it'll be necessary to implement a new OpenAPI schema that would strictly match the request/response formats specified by Manticore's HTTP API and to regenerate all the clients with that schema.

**Comment by sanikolaev** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1808

**Comment by sanikolaev** [comment]
> Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1808

Done.

Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1807

**Comment by donhardman** [comment]
As discussed before, we should try our best to simplify the code following common sense and principles to be as concise as possible while still doing the job.

It feels like we can try to reduce the lines of code we use for creating instances and just expose a kind of `Client` to interact with. We should try to remove instances where we have JSON as a string in our examples and use native data structures instead. The main goal should be to use concise code that is sufficient to accomplish its purpose.

Some examples to consider looking at to understand what I mean:

Now:
```go
query := map[string]interface{} {"query_string": "Title"}
result := client.Search("test", query)
```

Good to be:
```go
query := map[string]interface{} {"query_string": "Title"}
result := client.Search("test", query)
```

Now:
```go
docs := []string {
  "{\"insert\": {\"index\" : \"test\", \"id\" : 1, \"doc\" : {\"title\" : \"Title 1\"}}}",
  "{\"insert\": {\"index\" : \"test\", \"id\" : 2, \"doc\" : {\"title\" : \"Title 2\"}}}",
}
apiClient.IndexAPI.Bulk(context.Background()).Body(strings.Join(docs[:], "\n")).Execute()
```

Good to be:
```go
docs := map[string]interface{} {
"insert":  ...
}
```

Now:
```ts
const config = new Configuration({
  basePath: 'http://localhost:9308/',
})
const indexApi = new IndexApi(config);
const searchApi = new SearchApi(config);
```

Good to be:
```ts
const client = new Client({
  basePath: 'http://localhost:9308/',
})
```

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/openapi/commit/2d63bf1b0b6e95d92d305c7232d20680a72eb752
