### ISSUE TITLE
composite aggregation

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/openapi#17]
We need to include the new functionality in the JSON interface - composite aggregation - https://manual.manticoresearch.com/dev/Searching/Grouping#GROUP-BY-multiple-fields-at-once

**Comment by Nick-S-2018** [comment]
Done. Added dev releases in https://github.com/manticoresoftware/manticoresearch-javascript/commit/071d81e8d3cbf43cd6c0b77d728f26c26df91a2a, https://github.com/manticoresoftware/manticoresearch-typescript/commit/a74d575bfb50e8ab1b614ae7130cf0da3f65f8fd, https://github.com/manticoresoftware/manticoresearch-python/commit/f2d69ba10b924478a3d3e13232bb381f13bcfd7b, https://github.com/manticoresoftware/manticoresearch-go/commit/7e2c2e97b9b96755e47e23d7280d473bd3a23785, https://github.com/manticoresoftware/manticoresearch-net/commit/b5d25e33672ebef2b6c52086cc902899637958d8, https://github.com/manticoresoftware/manticoresearch-java/commit/2424d49c5c6f12363397c7b2ce884affb00a2e5a
