### ISSUE TITLE
c#/.net client missed

### ISSUE THREAD

**Issue by thenik** [manticoresoftware/openapi#4]
Hello,

I see that you have an option to generate c#/.net client for manticore software API.
Could you add it the same way as you do for Java, Python, Js ?

Thanks!

**Comment by sanikolaev** [comment]
Hello

Yes. There's a PR about it https://github.com/manticoresoftware/openapi/pull/3

Can you help with beta testing the generated client once it's merged?

**Comment by thenik** [comment]
> Hello
> 
> Yes. There's a PR about it #3
> 
> Can you help with beta testing the generated client once it's merged?

Yes, I can!
 I migrate now WINDOWS .net 4.6.2 console app to LINUX .net 6 app.
so I am ready to test it.
How I can test it ?

**Comment by sanikolaev** [comment]
I'll check with the developers on what's left within the PR and will let you know.

**Comment by thenik** [comment]
![image](https://user-images.githubusercontent.com/1731242/176369244-62e60e21-4e26-4798-acfc-c171e9882f5d.png)

here is my config Debian 11 with Manticore

here is my c# code with your .net client project
`//var basePath = "http://38.242.129.231:9308/";
var basePath = "http://38.242.129.231:9312/";
//var apiClient = new ManticoreSearch.Client.ApiClient(basePath);
//var a = new ManticoreSearch.Client.RequestOptions() { };
//var resA = apiClient.Put<object>("p", a);
var indexApi = new ManticoreSearch.Api.IndexApi(basePath);
var doc= new Dictionary<string, object>();
doc["name"] = "Nikolai";
var req = new ManticoreSearch.Model.InsertDocumentRequest("mytestindex", null, 0, doc);
var res = indexApi.Insert(req);
`

it fails 
![image](https://user-images.githubusercontent.com/1731242/176369643-c0ae4291-d122-4433-9e45-248afe19bbad.png)


ManticoreSearch.Client.ApiException: 'Error calling Insert: {"error":"//json/insert - unsupported endpoint"}'

any ideas how to fix it?

**Comment by sanikolaev** [comment]
> here is my c# code with your .net client project

What exactly .net client project?

**Comment by thenik** [comment]
I took code from here 
https://github.com/mihaj/openapi/tree/net-client/out/manticoresearch-net/src/ManticoreSearch

**Comment by thenik** [comment]
new info

![image](https://user-images.githubusercontent.com/1731242/176377033-7330ba71-ba8d-4fa9-a7a0-74bd013f3909.png)

I removed leading slash /

andI got new type of error

![image](https://user-images.githubusercontent.com/1731242/176377089-8244b93b-78a3-4de3-9c73-42299bf1dd16.png)


Any ideas ?

**Comment by thenik** [comment]
right, there is no INDEX
but the I try to create it via SQL

var utils = new UtilsApi(basePath);
var sql = $@"
CREATE TABLE products (
id int ,
product_rec_id int ,
product_name text ,
sku text ,
manufacturer_name text ,
category_name text stored,
clp_file_name text stored,
dump text stored
)";
utils.Sql(sql);

this code  fails... with 

ManticoreSearch.Client.ApiException: 'Error calling Sql: {"error":"query missing"}'


![image](https://user-images.githubusercontent.com/1731242/176410113-bd91e61b-1c7f-43c1-b1e1-ede5dc3e460a.png)


and here I also adjusted original .net client code, remove leading slash/ for sql enpoint call...


Any ideas ?

**Comment by thenik** [comment]
![image](https://user-images.githubusercontent.com/1731242/176410979-06ddc089-3618-45c9-bfa2-ed91a44ee115.png)

**Comment by thenik** [comment]
UtilsApi.Sql does not work...

**Comment by sanikolaev** [comment]
> Any ideas ?

Let's wait until the PR is complete. It perhaps misses something and it's too early for testing it. Or, if you want, you can try to debug the client itself and e.g. in this case figure out why the `query` is missing and then put a comment to the PR.

**Comment by thenik** [comment]
Do you know when this PR will be ready? Any expectations?

**Comment by thenik** [comment]
I found that /sql accepts only SELECT * queries
if you want to run any query you have to send request to /sql?raw
https://manual.manticoresearch.com/Connecting_to_the_server/HTTP#/sql?mode=raw
but .net project sends to 
/sql?raw_response=true
and does not fill Payload... wow looks like that nobody in the word used this library.

**Comment by sanikolaev** [comment]
> Do you know when this PR will be ready? Any expectations?

@mihaj is the PR still of interest for you?

**Comment by sanikolaev** [comment]
We are going to prioritize working on the client this week.

**Comment by mihaj** [comment]
Sadly, I can not work on this at the moment.

**Comment by Nick-S-2018** [comment]
@thenik we've published beta version of the client [here](https://github.com/manticoresoftware/manticoresearch-net)

**Comment by sanikolaev** [comment]
@thenik Did you have a chance to look into the new client beta version?

**Comment by thenik** [comment]
sorry, I will check later.  Thanks for the new version!

**Comment by thenik** [comment]
I checked this https://github.com/manticoresoftware/manticoresearch-net and I got a strange result:

![image](https://user-images.githubusercontent.com/1731242/177940739-febfcce2-061d-4bc3-a3f3-1acd49a86743.png)

Solution is broken...
How did you test it ?

**Comment by sanikolaev** [comment]
We know nothing about your IDE and C# in general. We didn't test it, we just generated it using OpenAPI generator. Can you check what may be wrong with it, so we can change the way we generate it?

**Comment by thenik** [comment]
My IDE is visual studio 2022 community.  (it supports WIndows and Mac)
If you use linux you can test your library via c# Rider IDE, it is free for 30 days.
Hope it will help you to adjust it.

![image](https://user-images.githubusercontent.com/1731242/178219316-3337a001-de2f-4565-9435-a7f30a95b234.png)

I think that something is wrong with your .csproj file for  the library.

I tried to understand the core of the issue (opened in notepad) what is wrong but it is too hard for me... generated files is too complex.

Maybe better to create this file manually ?

**Comment by Nick-S-2018** [comment]
We've regenerated the client and checked it in Visual Studio 22.   Please try the new version https://github.com/manticoresoftware/manticoresearch-net

**Comment by thenik** [comment]
thanks, now I can open it!

but I cannot run any tests - all test files are empty

![image](https://user-images.githubusercontent.com/1731242/178355014-23f35996-f931-417f-82b9-93b7f6526066.png)




I have a Manticore installation, will be nice if I insert IP address into test code and will get some results.
The same way as I see for python code you have now.

May you add any real index creation, document insertion and search result geting into code for c#  tests ?

**Comment by Nick-S-2018** [comment]
We've added the C# client and basic auto tests for it [here](https://github.com/manticoresoftware/manticoresearch-net/commit/593638fca5a3f8f8c5242d972c64fe21610f4817)
